# Generated by Django 3.2 on 2021-10-04 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0002_coordinates_fetched_from_api_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='fetched_from_api_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
