# Generated by Django 3.2 on 2021-10-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coordinates', '0006_auto_20211005_0504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinates',
            name='coordinates',
        ),
    ]
