# Generated by Django 3.2 on 2021-09-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
