# Generated by Django 3.2 on 2021-09-17 12:34

from django.db import migrations


def calculate_price_by_order_item(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    order_items = OrderItem.objects.filter(price=0).prefetch_related('product')

    for item in order_items.iterator():
        item.price = item.quantity * item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_price_by_order_item),
    ]
