# Generated by Django 3.2 on 2021-09-17 12:34

from django.db import migrations
from django.db.models import F


def calculate_price_by_order_item(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.filter(price=0).prefetch_related('product'):
        item.price = item.quantity * item.product.price
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_price_by_order_item),
    ]
