# Generated by Django 3.2 on 2021-09-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новый'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Завершён')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
