# Generated by Django 3.2 on 2021-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20210918_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
