# Generated by Django 3.2 on 2021-09-19 11:44

from foodcartapp.models import Restaurant
from django.db import migrations
from foodcartapp.utils import fetch_coordinates
from django.conf import settings
import json


def fill_restaurants_coordinates(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'Restaurant')
    for rest in Restaurant.objects.all():
        long, lat = fetch_coordinates(
            settings.YA_API_KEY,
            rest.address    
        )
        coordinates = json.dumps({'long': long, 'lat': lat})
        rest.coordinates = coordinates 
        rest.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_restaurant'),
    ]

    operations = [
        migrations.RunPython(fill_restaurants_coordinates),
    ]
