# Generated by Django 3.2 on 2021-09-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_auto_20210919_1142'),
        ('foodcartapp', '0052_auto_20210919_1144'),
    ]

    operations = [
    ]
