# Generated by Django 3.2 on 2021-09-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_merge_0051_auto_20210919_1142_0052_auto_20210919_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100, verbose_name='Адрес доставки')),
                ('coordinates', models.JSONField(verbose_name='Координаты')),
            ],
            options={
                'verbose_name': 'Координаты',
                'verbose_name_plural': 'Координаты',
            },
        ),
    ]
