# Generated by Django 3.2 on 2021-09-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_coordinates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
