# Generated by Django 3.2 on 2021-10-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0060_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='long',
            field=models.DecimalField(decimal_places=8, default=1, max_digits=11, verbose_name='долгота'),
            preserve_default=False,
        ),
    ]
