# Generated by Django 3.2 on 2021-10-16 05:25

from django.db import migrations
from foodcartapp.coordinates_api_functions import parse_coordinates


def fill_long_lat(apps, schema_editor):
    Restaurant = apps.get_model('foodcartapp', 'Restaurant')
    Restaurant = Restaurant.objects.all()

    for rest in Restaurant:
        long_lat = parse_coordinates(rest.coordinates)
        long = long_lat[0]
        lat = long_lat[1]
        rest.long = long
        rest.lat = lat
        rest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20211016_0524'),
    ]

    operations = [
        migrations.RunPython(fill_long_lat),
    ]
