# Generated by Django 3.2 on 2021-10-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_auto_20211016_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='coordinates',
        ),
    ]
